api:
  consumer_key: 'REGISTER YOUR APP AND GET CONSUMER KEY/SEC HERE:'
  consumer_sec: 'http://www.plurk.com/PlurkApp/register'
  key: 'AND GET ACCESS TOKEN HERE:'
  sec: 'http://www.plurk.com/OAuth/test/'
format: '%(karma).2f (auto) #4ji'
#
# available format:
#   karma:        %(karma).2f
#   username:     %(nick_name)s
#   screen name   %(display_name)s
#   full name     %(full_name)s
#   location:     %(location)s
#   relationship: %(relationship)s
#   language:     %(default_lang)s
#   timezone:     %(timezone)s
#
log_dir: '~/tmp (FOR diff_emos COMMAND)'
emos_html: 'PATH TO HTML-FILE (FOR emos_html COMMAND)'
#
# see also <http://docs.python.jp/2/library/logging.config.html#id3>'
#
logging:
  version: 1
  formatters:
    tiny:
      format: '%(message)s'
    daily:
      format: '%(asctime)s.%(msecs)d [%(levelname)4.4s] %(filename)s:%(lineno)d: %(message)s'
      datefmt: '%H:%M:%S'
  handlers:
    console:
      level: 'DEBUG'
      formatter: 'tiny'
      class: 'logging.StreamHandler'
    logfile:
      level: 'INFO'
      formatter: 'daily'
      class: 'logging.handlers.TimedRotatingFileHandler'
      filename: '/tmp/logging.log'
      when: 'd'
      encoding: 'UTF-8'
    email:
      level: 'CRITICAL'
      formatter: 'tiny'
      class: 'logging.handlers.SMTPHandler'
      mailhost: !!python/tuple ['HOST', PORT]
      fromaddr: 'from@addr'
      toaddrs: ['to@addr']
      subject: '[plurk4ji][logging] critical issue'
      credentials: !!python/tuple ['username', 'password']
  root:
    handlers: ['console', 'logfile', 'email']
    level: 'DEBUG'
